### ISSUE TITLE
Release 7.7.3: Module '"/node_modules/vite-plugin-vue-devtools/dist/vite"' has no default export.

### ISSUE THREAD

**Issue by Qu33zZ** [vuejs/devtools#861]
The latest (7.7.3) version that was just released is broken. Downgrading to 7.7.0 solves this problem

**Comment by webfansplz** [comment]
Upgrade to v7.7.4 and try again 🙏.

**Comment by webfansplz** [comment]
Can you provide a mini repo? Thanks 🙏

**Comment by LaurentChardin** [comment]
Same error here : latest version is generating the same issue for me : VScode is actually alerting me.

<img width="842" alt="Image" src="https://github.com/user-attachments/assets/7db5b7bc-a5ef-42be-b81d-e2df8e5f83a2" />

Project was working fine, just failed after a version bump.

**Comment by webfansplz** [comment]
> Same error here : latest version is generating the same issue for me : VScode is actually alerting me.
> 
> <img alt="Image" width="842" src="https://private-user-images.githubusercontent.com/504748/434422536-7db5b7bc-a5ef-42be-b81d-e2df8e5f83a2.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3NDQ4MjA4MDMsIm5iZiI6MTc0NDgyMDUwMywicGF0aCI6Ii81MDQ3NDgvNDM0NDIyNTM2LTdkYjViN2JjLWE1ZWYtNDJiZS1iODFkLWUyZGY4ZTVmODNhMi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjUwNDE2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI1MDQxNlQxNjIxNDNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0xZDIyMTM3OTcwMTMwOTI5YWFjM2NlNzU3ZGFlOGM5ZWIxODI0YjdlMDdiNTE0ZTU1NzJiNTUzMjJhZGRkMGZhJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.n2cBMx31tJjgMRTZik9jDh06cjnMCd5Iny9Ylivxaik">
> Project was working fine, just failed after a version bump. And using v7.7.4

The plugin works fine, but there is a issue with the type prompt, right?

**Comment by EDM115** [comment]
+1, also seeing the same issue. Happens on build :  
```pwsh
> edm115-website@0.6.3 build /home/runner/work/website/website
> run-s type-check "build-only {@}" --


> edm115-website@0.6.3 type-check /home/runner/work/website/website
> vue-tsc --build

Error: vite.config.ts(11,[8](https://github.com/EDM115/website/actions/runs/14497722655/job/40669606316?pr=424#step:6:9)): error TS1192: Module '"/home/runner/work/website/website/node_modules/.pnpm/vite-plugin-vue-devtools@7.7.4_rollup@4.40.0_vite@6.3.0_@types+node@22.14.1_jiti@2.4.2_lightningcss@1.2[9](https://github.com/EDM115/website/actions/runs/14497722655/job/40669606316?pr=424#step:6:10).3_sass-embedded@1.86.3_yaml@2.7.1__vue@3.5.13_typescript@5.8.3_/node_modules/vite-plugin-vue-devtools/dist/vite"' has no default export.
 ELIFECYCLE  Command failed with exit code 2.
ERROR: "type-check" exited with 2.
 ELIFECYCLE  Command failed with exit code 1.
Error: Process completed with exit code 1.
```

**Comment by webfansplz** [comment]
Upgrade to v7.7.5 and try again 🙏.

**Comment by EDM115** [comment]
@webfansplz i can confirm 7.7.5 doesn't have the issue : 
![Image](https://github.com/user-attachments/assets/afdef225-e92c-4475-a68f-11f73a2601d7)

@LaurentChardin can you confirm ?

**Comment by nsteinmetz** [comment]
@webfansplz I can confirm it works in my case with version 7.7.5 - thanks !
